### ISSUE TITLE
Pipe definition fetch error

### ISSUE THREAD

**Issue by vinothav** [yves-vogl/aws-eks-helm-deploy#1]
Hi,

I tried to use the pipe as described in the Readme file. Below is the step from my bitbucket-pipeline.yaml 

`                
      - step:
          name: Deploy helm chart in EKS test environment
          deployment: test-cicd
          script:
            - echo $BITBUCKET_COMMIT
            - pipe: yvogl/aws-eks-helm-deploy:1.0.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_DEVOPS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_DEVOPS_SECRET
                AWS_REGION: $AWS_CLUSTER_REGION
                CLUSTER_NAME: xxxxxxxx
                CHART: ./xxxx
                SET: [
                    'image.tag=${BITBUCKET_COMMIT}'
                ]
                VALUES: values-test.yaml
                NAMESPACE: xxxxxxx
                DEBUG: 'true'`

But on executing the pipeline, it fails immediately with Configuration Error: Pipe definition fetch error. with no logs provided event when the Debug flag is set to true.

Am I missing something here? kindly advice.

**Comment by maxmarcon** [comment]
Same problem here

**Comment by yves-vogl** [comment]
Hi all. Sorry for showing up late here. I'll have a look into this.

**Comment by yves-vogl** [comment]
I was able to [reproduce the error](https://bitbucket.org/yvogl/aws-eks-helm-deploy-test/addon/pipelines/home#!/results/2) and will debug it

**Comment by maxmarcon** [comment]
Awesome! Thank you 🎉

**Comment by yves-vogl** [comment]
It was a simple documentation issue. As it's a custom pipe you've to use the docker syntax.

See https://github.com/yves-vogl/aws-eks-helm-deploy/commit/4c5e2b786bb1f3a5cd97b7567a0cf4f6d16dbdf7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R10

 I guess I specified it in the documentation like I'd have done for an official pipe as [I submitted a pull request to Atlassian](https://bitbucket.org/bitbucketpipelines/official-pipes/pull-requests/307).

Unfortunately they did just accept vendor pipes at that moment - so if you'd like to have the pipe included in the official pipes, [you can vote here](https://jira.atlassian.com/browse/BCLOUD-20858).

Thank you for using this pipe. Feel free to open a pull request with updated dependencies - I'd be happy to merge it.

**Comment by maxmarcon** [comment]
Thank you for reacting and fixing the issue so quickly @yves-vogl 🥇!!! I will test the pipe again shortly.

I really hope it gets accepted as an official pipe... I'll be sure to cast my vote! 👍
