### ISSUE TITLE
Allow specification of chart repository and version

### ISSUE THREAD

**Issue by martinky** [yves-vogl/aws-eks-helm-deploy#7]
Please allow the installation of Helm Chart from a repository by specifying the `--repo` option and (optionally) the `--version` option.

This could be exposed as following pipe variables:

- `CHART_REPO` - optional
- `CHART_VERSION` - optional

Specifying `CHART_REPO` should result in following Helm command line:

```
helm upgrade --install --repo <CHART_REPO> <RELEASE_NAME> <CHART>
```

And if `CHART_VERSION` is also specified:

```
helm upgrade --install --repo <CHART_REPO> --version <CHART_VERSION> <RELEASE_NAME> <CHART>
```

Prerequisite: Removal of the existence check for the local file `Chart.yaml` from `client.py` - this prevents the user from specifying the Chart by name or absolute URL or from providing a packaged chart in .tgz archive.

Documentation: https://helm.sh/docs/helm/helm_install/

**Comment by yves-vogl** [comment]
I merged your PR to complete the prerequisite. Thank you!
